import Head from "next/head";
import localFont from "next/font/local";
import Header from "@/modules/header/header";
import { useState } from "react";
import About from "@/modules/about/about";
import Services from "@/modules/services/services";
import NameSelection from "@/modules/name-selection/nameSelection";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export default function Home() {
  const [isModal, setIsModal] = useState(false);

  return (
    <>
      <Head>
        <title>Lumos test task</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Header />
      <main>
        <About />
        {/* {isModal && } */}
        <Services />
        <NameSelection />
      </main>
    </>
  );
}
